name: Build

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-24.04
    container: ghcr.io/cognipilot/ci-minimal:v0.0.1
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Set path
        run: |
          echo "/github/home/.local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: spinali

      - name: Initialize
        working-directory: spinali
        run: |
          west init -l .
          west update
          west blobs fetch hal_afbr
          ./scripts/cyecca_install

      - name: Format Check
        working-directory: spinali
        run: |
          west format -c

      - name: Twister Tests
        working-directory: spinali
        run: |
          west test
